"""Master plan §9 — PostgreSQL move, phase 1 (SQLAlchemy abstraction).

Scaffolding only: builds a SQLAlchemy engine URL from environment, for either
SQLite (current default, matches database.py's DB_PATH resolution) or
PostgreSQL (opt-in, docker-compose `postgres` service). Nothing in
logic/*.py uses this engine yet — every existing read/write still goes
through database.py's raw sqlite3 connections. This module exists so
Alembic has a target and the next slice (porting raw SQL to SQLAlchemy
Core) has a stable place to plug in, without touching any working code path.

Env vars:
  SCHEDULER_DB_BACKEND=sqlite (default) | postgres
  SCHEDULER_DB_PATH        — SQLite file path (sqlite backend; reuses the
                              same var database.py already reads)
  SCHEDULER_PG_DSN         — full postgres DSN (postgres backend), e.g.
                              postgresql+psycopg://user:pass@host:5432/chronos
"""

from __future__ import annotations

import os

from sqlalchemy import Engine, MetaData, create_engine


def database_url() -> str:
    backend = (os.environ.get("SCHEDULER_DB_BACKEND") or "sqlite").strip().lower()
    if backend == "postgres":
        dsn = (os.environ.get("SCHEDULER_PG_DSN") or "").strip()
        if not dsn:
            raise RuntimeError("SCHEDULER_DB_BACKEND=postgres requires SCHEDULER_PG_DSN")
        # SCHEDULER_PG_DSN is a plain libpq DSN (what db_compat.py's raw
        # psycopg.connect() and ad-hoc scripts expect). SQLAlchemy instead
        # needs the driver named in the URL scheme, and defaults to the
        # (unrelated, not installed here) psycopg2 package for a bare
        # "postgresql://" — rewrite to "postgresql+psycopg://" for psycopg 3.
        if dsn.startswith("postgresql://"):
            dsn = "postgresql+psycopg://" + dsn[len("postgresql://") :]
        return dsn
    if backend != "sqlite":
        raise RuntimeError(f"Unknown SCHEDULER_DB_BACKEND={backend!r} (expected sqlite or postgres)")

    from database import DB_PATH  # reuse the same path resolution as the live app

    if DB_PATH.startswith("file:"):
        # SQLAlchemy's sqlite driver takes a plain filesystem path, not a
        # sqlite3 URI (mode=memory&cache=shared etc.) — in-memory/URI paths
        # aren't representable here yet; real files are.
        raise RuntimeError("SQLAlchemy sqlite backend does not support sqlite3 URI paths (mode=memory, etc.)")
    return f"sqlite:///{DB_PATH}"


def get_engine() -> Engine:
    return create_engine(database_url())


def reflect_metadata(engine: Engine | None = None) -> MetaData:
    """Reflect the live database's actual schema into SQLAlchemy metadata.

    Deliberately reflection, not a hand-transcribed model: database.py's ~40
    tables are the source of truth (raw CREATE TABLE statements built up
    over many migrations) and re-typing them by hand risks drifting from
    what's actually on disk. This metadata is what the baseline Alembic
    migration is autogenerated from — the migration then becomes the
    portable (sqlite -> postgres) source of truth going forward.

    Reflects from SCHEDULER_DB_REFLECT_PATH if set, else the same source
    `database_url()` would use. The separate var exists only so the
    one-time baseline migration can be generated by diffing this (the real,
    populated dev DB) against an empty scratch connection pointed at by
    SCHEDULER_DB_PATH — ordinary use leaves it unset and both resolve to
    the same database.
    """
    if engine is None:
        override = (os.environ.get("SCHEDULER_DB_REFLECT_PATH") or "").strip()
        if override:
            engine = create_engine(f"sqlite:///{override}")
        else:
            engine = get_engine()
    metadata = MetaData()
    metadata.reflect(bind=engine)
    return metadata
