"""
Canonical vertical-slice registry for Dodgeville PD Scheduler.

Each slice groups what changes together: UI entry, logic, CLI, tests, and permissions.
Shared infrastructure (database, validators, theme shell) lives in SHARED_KERNEL — not slices.
"""

from __future__ import annotations

from typing import Any, Dict, List, Optional, TypedDict


class SliceDef(TypedDict, total=False):
    id: str
    name: str
    summary: str
    status: str  # complete | partial | planned
    ui_pages: List[str]
    ui_mixin: str
    logic: List[str]
    logic_extra: List[str]  # e.g. database.backup_database
    validators: List[str]
    cli: List[str]
    permissions: List[str]
    tables: List[str]
    tests: List[str]
    scenarios: List[str]
    verify: List[str]  # dev.py commands that exercise this slice
    touch_together: List[str]
    future_module: str


SHARED_KERNEL: Dict[str, Any] = {
    "description": "Cross-cutting code — edit only when the change affects multiple slices.",
    "files": [
        "config.py",
        "models.py",
        "database.py",
        "validators.py",
        "auth_password.py",
        "permissions.py",
        "paths.py",
        "audit.py",
        "ui/app.py",
        "ui/theme.py",
        "ui/widgets.py",
        "ui/helpers.py",
        "ui/login.py",
        "main.py",
        "dev.py",
    ],
    "notes": [
        "validators.py remains the single source of truth for pre-checks.",
        "analytics.py is report-oriented; slice-specific report functions are listed on the reports slice.",
        "Import logic via `import logic` — package re-exports slice modules (logic/exports.py, logic/dashboard.py, etc.).",
    ],
}


SLICES: List[SliceDef] = [
    {
        "id": "dashboard",
        "name": "Command Post Dashboard",
        "summary": "Role-scoped ops home: stats, alerts, coverage gap board, on-duty strip, My Week, quick actions.",
        "status": "complete",
        "ui_pages": ["dashboard"],
        "ui_mixin": "ui/dashboard_pages.py",
        "logic": ["get_dashboard_insights", "get_coverage_gap_board", "get_hours_watch", "get_officer_schedule_window"],
        "validators": [],
        "cli": ["reports summary"],
        "permissions": ["reports.view", "login"],
        "tables": ["day_off_requests", "schedule_overrides", "notifications"],
        "tests": ["tests/test_analytics.py"],
        "scenarios": [],
        "verify": ["smoke", "ui-smoke"],
        "touch_together": ["analytics.py", "ui/dashboard_pages.py", "logic/dashboard.py"],
        "future_module": "logic/dashboard.py",
    },
    {
        "id": "roster",
        "name": "Officer Roster",
        "summary": "Patrol roster CRUD, photos, CSV import, title/squad/shift assignment, pay-period hours on rows.",
        "status": "complete",
        "ui_pages": ["officers"],
        "ui_mixin": "ui/officers_pages.py",
        "logic": [
            "add_officer",
            "update_officer",
            "delete_officer",
            "get_officers_by_seniority",
            "get_officer_by_id",
            "import_roster_from_csv",
            "get_pay_period_hours_by_officer",
        ],
        "validators": ["validate_officer_profile", "validate_officer_email"],
        "cli": ["officers list", "officers add", "officers update", "officers delete"],
        "permissions": ["officers.manage"],
        "tables": ["officers"],
        "tests": ["tests/test_officer_crud.py", "tests/test_roster_import.py"],
        "scenarios": [],
        "verify": ["smoke", "ui-smoke"],
        "touch_together": [
            "logic/officers.py",
            "validators.py",
            "ui/officers_pages.py",
            "cli.py",
            "seed_data.py",
        ],
        "future_module": "logic/officers.py",
    },
    {
        "id": "day-off-requests",
        "name": "Day-Off Requests",
        "summary": "Submit and approve time off with bump preview, cascade, manual review, and request ledger.",
        "status": "complete",
        "ui_pages": ["requests"],
        "ui_mixin": "ui/requests_pages.py",
        "logic": [
            "create_day_off_request",
            "process_day_off_request",
            "get_day_off_requests",
            "get_day_off_requests_for_viewer",
            "get_pending_day_off_requests",
            "suggest_bump_chain",
            "validate_bump_feasibility",
            "plan_bump_chain",
            "bulk_approve_auto_ok_requests",
            "bulk_reject_pending_requests",
        ],
        "validators": [
            "validate_day_off_request",
            "validate_request_status",
            "validate_minimum_rest_gap",
            "validate_manual_override",
        ],
        "cli": ["requests pending", "requests list", "requests approve", "requests reject"],
        "permissions": ["requests.submit", "requests.submit_any", "requests.approve"],
        "tables": ["day_off_requests", "schedule_overrides"],
        "tests": ["tests/test_logic.py", "tests/test_regressions.py", "tests/test_validators.py"],
        "scenarios": ["S-01", "S-07", "S-09", "S-10"],
        "verify": ["smoke", "scenarios", "audit"],
        "touch_together": [
            "logic/requests.py",
            "logic/scheduling.py",
            "logic/rust_bridge.py",
            "rust/scheduler_core/Cargo.toml",
            "validators.py",
            "config.py",
            "ui/requests_pages.py",
            "cli.py",
            "tests/test_logic.py",
            "tests/test_regressions.py",
        ],
        "future_module": "logic/requests.py",
    },
    {
        "id": "shift-swaps",
        "name": "Shift Swaps",
        "summary": "Exchange shifts between officers with feasibility checks and dual override creation.",
        "status": "complete",
        "ui_pages": ["swaps"],
        "ui_mixin": "ui/requests_pages.py",
        "logic": [
            "create_shift_swap_request",
            "process_shift_swap",
            "get_shift_swap_requests",
            "get_pending_shift_swap_requests",
            "validate_swap_feasibility",
        ],
        "validators": ["validate_minimum_rest_gap"],
        "cli": ["swaps pending", "swaps approve", "swaps reject"],
        "permissions": ["swaps.submit", "swaps.approve"],
        "tables": ["shift_swaps", "schedule_overrides"],
        "tests": ["tests/test_notifications_swaps_exports.py", "tests/test_regressions.py"],
        "scenarios": ["S-11"],
        "verify": ["scenarios", "ui-smoke"],
        "touch_together": [
            "logic/requests.py",
            "logic/scheduling.py",
            "validators.py",
            "ui/requests_pages.py",
            "cli.py",
        ],
        "future_module": "logic/requests.py",
    },
    {
        "id": "schedules",
        "name": "Schedules & Gantt",
        "summary": "Original/current monthly calendars, 14-day Gantt, publish/sync, diff, manual coverage from calendar.",
        "status": "complete",
        "ui_pages": ["base_schedule", "live_schedule", "timeline"],
        "ui_mixin": "ui/schedule_pages.py",
        "logic": [
            "build_schedule_matrix",
            "get_monthly_summary_from_snapshot",
            "ensure_original_monthly_schedule",
            "sync_updated_schedule",
            "compare_base_updated_schedule",
            "create_manual_coverage_override",
            "get_officer_schedule_window",
            "get_schedule_snapshot",
        ],
        "validators": ["validate_cycle_date"],
        "cli": ["export schedule", "schedule-diff", "overrides assign"],
        "permissions": [
            "schedule.base.view",
            "schedule.base.publish",
            "schedule.updated.view",
            "schedule.updated.sync",
            "schedule.updated.edit",
            "schedule.export_own",
        ],
        "tables": ["schedule_snapshots", "schedule_overrides"],
        "tests": ["tests/test_timecard_schedules.py", "tests/test_logic.py"],
        "scenarios": [],
        "verify": ["smoke", "ui-smoke"],
        "touch_together": [
            "logic/snapshots.py",
            "logic/scheduling.py",
            "logic/rust_bridge.py",
            "rust/scheduler_core/Cargo.toml",
            "ui/schedule_pages.py",
            "cli.py",
            "config.py",
        ],
        "future_module": "logic/snapshots.py",
    },
    {
        "id": "payroll-timecard",
        "name": "Payroll & Timecard",
        "summary": "Timecard entry, pay-period totals, payroll ledger, lock period, position pay rates.",
        "status": "complete",
        "ui_pages": ["timecard", "banked_time", "payroll"],
        "ui_mixin": "ui/payroll_pages.py",
        "logic": [
            "get_officer_title_options",
            "add_custom_officer_title",
            "save_timecard_entry",
            "get_timecard_period",
            "get_banked_time_summary",
            "get_bank_transactions",
            "get_timecard_entries_for_scope",
            "get_payroll_entries",
            "create_payroll_entry",
            "lock_pay_period",
            "get_pay_period_hours_summary",
            "calculate_pay_for_entry",
            "get_pay_code_rules",
            "save_pay_code_rules",
            "search_pay_period_by_date",
            "list_pay_periods_catalog",
            "format_pay_period_label",
            "is_current_pay_period",
            "count_pay_periods_in_year",
            "monthly_pay_to_per_pay_period",
            "suggested_hourly_rate_for_title",
            "get_flsa_settings",
            "save_flsa_settings",
        ],
        "validators": [],
        "cli": ["pay-period status", "pay-period lock", "csv payroll", "csv timecard"],
        "permissions": [
            "timecard.view_own",
            "timecard.edit_own",
            "timecard.view_all",
            "timecard.edit_all",
            "timecard.submit",
            "timecard.approve",
            "payroll.view_own",
            "payroll.view_all",
            "payroll.edit",
            "payroll.lock_period",
        ],
        "tables": ["payroll_entries", "timecard_entries", "timecard_approvals", "pay_period_locks"],
        "tests": [
            "tests/test_payroll.py",
            "tests/test_timecard_schedules.py",
            "tests/test_position_pay.py",
            "tests/test_pay_code_rules.py",
            "tests/test_banked_time.py",
        ],
        "scenarios": [],
        "verify": ["smoke", "ui-smoke"],
        "touch_together": [
            "logic/payroll.py",
            "logic/banked_time.py",
            "ui/payroll_pages.py",
            "ui/banked_time_pages.py",
            "cli.py",
        ],
        "future_module": "logic/payroll.py",
    },
    {
        "id": "notifications",
        "name": "Alerts & Notifications",
        "summary": "In-app alerts inbox, read/mark-all, navigation to related records, schedule-sync notify hooks.",
        "status": "complete",
        "ui_pages": ["notifications"],
        "ui_mixin": "ui/notifications_pages.py",
        "logic": [
            "get_notifications",
            "mark_notification_read",
            "mark_all_notifications_read",
            "get_unread_notification_count",
            "create_notification",
        ],
        "validators": [],
        "cli": ["notifications list", "notifications read", "notifications read-all"],
        "permissions": ["notifications.manage", "login"],
        "tables": ["notifications"],
        "tests": ["tests/test_notifications_swaps_exports.py", "tests/test_regressions.py"],
        "scenarios": [],
        "verify": ["ui-smoke"],
        "touch_together": [
            "logic/requests.py",
            "ui/notifications_pages.py",
            "ui/dashboard_pages.py",
            "cli.py",
        ],
        "future_module": "logic/requests.py",
    },
    {
        "id": "reports-analytics",
        "name": "Ops Reports & Analytics",
        "summary": "Coverage, OT, labor budget, equitable OT ledger, audit log, department settings, PDF/CSV exports.",
        "status": "complete",
        "ui_pages": ["reports"],
        "ui_mixin": "ui/feature_pages.py",
        "logic": [
            "get_coverage_report",
            "get_overtime_alerts",
            "get_labor_budget_status",
            "get_equitable_ot_ledger",
            "get_audit_log",
        ],
        "logic_extra": [],
        "validators": [],
        "cli": ["reports summary", "reports coverage", "reports overtime", "audit-log list"],
        "permissions": ["reports.view", "reports.export", "audit.view", "admin.settings"],
        "tables": ["audit_log", "department_settings"],
        "tests": ["tests/test_analytics.py"],
        "scenarios": [],
        "verify": ["ui-smoke"],
        "touch_together": ["analytics.py", "logic/dashboard.py", "ui/feature_pages.py", "cli.py", "exports.py"],
        "future_module": "logic/exports.py",
    },
    {
        "id": "availability",
        "name": "Blackout Dates & Holidays",
        "summary": "Officer unavailability, schedule conflict warnings, department holiday calendar.",
        "status": "complete",
        "ui_pages": ["availability"],
        "ui_mixin": "ui/feature_pages.py",
        "logic": [
            "add_officer_availability",
            "get_schedule_conflicts",
            "is_officer_unavailable_on_date",
            "add_holiday",
            "delete_holiday",
            "get_holidays",
            "get_upcoming_holidays",
        ],
        "validators": [],
        "cli": ["availability list", "availability add", "availability conflicts"],
        "permissions": ["availability.view", "availability.manage_own", "availability.manage_all", "holidays.manage"],
        "tables": ["officer_availability", "holidays"],
        "tests": ["tests/test_analytics.py"],
        "scenarios": [],
        "verify": ["ui-smoke"],
        "touch_together": [
            "analytics.py",
            "logic/operations.py",
            "ui/feature_pages.py",
            "cli.py",
        ],
        "future_module": "logic/operations.py",
    },
    {
        "id": "shift-bidding",
        "name": "Shift Bidding",
        "summary": "Supervisors publish bid events; officers rank preferences; seniority resolves conflicts; simulator import.",
        "status": "complete",
        "ui_pages": ["availability", "simulator", "dashboard"],
        "ui_mixin": "ui/bid_pages.py",
        "logic": [
            "create_shift_bid_event",
            "publish_shift_bid_event",
            "submit_shift_bid_rankings",
            "finalize_shift_bid_event",
            "preview_shift_bid_awards",
            "update_shift_bid_assignments",
            "create_shift_bid_from_simulation",
            "get_shift_bid_participation_report",
            "save_simulator_scenario",
        ],
        "validators": [
            "validate_shift_bid_eligibility",
            "can_officer_work_day_band",
            "parse_bids_due_datetime",
        ],
        "cli": [
            "shift-bids list",
            "shift-bids post",
            "shift-bids submit",
            "shift-bids preview",
            "shift-bids finalize",
            "shift-bids import-sim",
            "shift-bids participation",
            "shift-bids assignments",
        ],
        "permissions": ["shift_bids.manage", "shift_bids.submit"],
        "tables": [
            "shift_bid_events",
            "shift_bid_options",
            "shift_bid_rankings",
            "simulator_scenarios",
        ],
        "tests": ["tests/test_tier2.py"],
        "scenarios": [],
        "verify": ["smoke", "check"],
        "touch_together": [
            "logic/bidding.py",
            "logic/rotation_preview.py",
            "logic/simulator_store.py",
            "ui/bid_pages.py",
            "ui/bid_dialogs.py",
            "ui/simulator_pages.py",
            "cli.py",
            "validators.py",
            "database.py",
            "tests/test_tier2.py",
        ],
        "future_module": "logic/bidding.py",
    },
    {
        "id": "open-shifts",
        "name": "Open Shifts",
        "summary": "Post claimable coverage gaps; officers claim open shifts from dashboard and availability hub.",
        "status": "complete",
        "ui_pages": ["availability", "dashboard"],
        "ui_mixin": "ui/feature_pages.py",
        "logic": ["create_open_shift", "get_open_shifts", "fill_open_shift"],
        "validators": [],
        "cli": ["open-shifts list", "open-shifts post"],
        "permissions": ["open_shifts.manage", "open_shifts.claim"],
        "tables": ["open_shifts"],
        "tests": ["tests/test_analytics.py"],
        "scenarios": [],
        "verify": ["ui-smoke"],
        "touch_together": [
            "logic/operations.py",
            "ui/feature_pages.py",
            "ui/dashboard_pages.py",
            "cli.py",
        ],
        "future_module": "logic/operations.py",
    },
    {
        "id": "user-accounts",
        "name": "User Accounts & Auth",
        "summary": "Login, demo users, role changes, password reset, setup wizard, permission gates.",
        "status": "complete",
        "ui_pages": ["users"],
        "ui_mixin": "ui/admin_pages.py",
        "logic": [
            "create_app_user",
            "update_app_user",
            "authenticate_user",
            "admin_reset_user_password",
            "complete_initial_setup",
            "list_login_users",
        ],
        "validators": ["validate_password", "validate_username", "validate_user_role_change"],
        "cli": ["users list", "users create", "users update", "users reset-password"],
        "permissions": ["users.manage", "users.edit_role", "login", "settings.manage"],
        "tables": ["app_users", "audit_log"],
        "tests": ["tests/test_users_security.py", "tests/test_auth.py", "tests/test_permissions.py"],
        "scenarios": [],
        "verify": ["smoke", "ui-smoke"],
        "touch_together": [
            "logic/users.py",
            "auth_password.py",
            "permissions.py",
            "ui/admin_pages.py",
            "ui/profile_dialog.py",
            "ui/login.py",
            "cli.py",
            "tests/test_users_security.py",
        ],
        "future_module": "logic/users.py",
    },
    {
        "id": "exports-ical",
        "name": "Schedule & Document Exports",
        "summary": "PDF schedule/payroll/requests, CSV roster, iCal per-officer export from timeline and CLI.",
        "status": "complete",
        "ui_pages": ["timeline", "payroll", "requests", "reports"],
        "ui_mixin": "ui/schedule_pages.py",
        "logic": [
            "export_schedule_pdf",
            "export_officer_schedule_ical",
            "export_payroll_pdf",
            "export_requests_pdf",
            "export_roster_csv",
        ],
        "validators": [],
        "cli": ["export schedule", "export ical", "export payroll", "csv roster"],
        "permissions": ["schedule.export_own", "reports.export"],
        "tables": [],
        "tests": ["tests/test_notifications_swaps_exports.py", "tests/test_analytics.py"],
        "scenarios": [],
        "verify": ["ui-smoke"],
        "touch_together": ["exports.py", "logic/exports.py", "cli.py"],
        "future_module": "logic/exports.py",
    },
    {
        "id": "simulator",
        "name": "Scenario Trainer",
        "summary": "Supervisor training simulator for rotation and staffing what-if (UI-only, no CLI).",
        "status": "complete",
        "ui_pages": ["simulator"],
        "ui_mixin": "ui/simulator_pages.py",
        "logic": ["run_schedule_simulation", "get_simulator_defaults_from_roster", "export_simulation_csv"],
        "validators": [],
        "cli": [],
        "permissions": ["simulator.use"],
        "tables": [],
        "tests": ["tests/test_simulator.py"],
        "scenarios": [],
        "verify": ["ui-smoke"],
        "touch_together": [
            "simulator.py",
            "logic/rust_bridge.py",
            "rust/scheduler_core/Cargo.toml",
            "ui/simulator_pages.py",
        ],
        "future_module": "logic/operations.py",
    },
    {
        "id": "database-backup",
        "name": "Database Backup",
        "summary": "Manual and auto SQLite backup from admin setup and CLI.",
        "status": "complete",
        "ui_pages": ["dashboard"],
        "ui_mixin": "ui/admin_pages.py",
        "logic": ["maybe_run_auto_backup"],
        "logic_extra": ["database.backup_database"],
        "validators": [],
        "cli": ["backup"],
        "permissions": ["database.backup"],
        "tables": [],
        "tests": ["tests/test_database_backup.py"],
        "scenarios": [],
        "verify": ["smoke"],
        "touch_together": ["database.py", "logic/operations.py", "cli.py"],
        "future_module": "logic/operations.py",
    },
]


def slice_ids() -> List[str]:
    return [s["id"] for s in SLICES]


def get_slice(slice_id: str) -> Optional[SliceDef]:
    for s in SLICES:
        if s["id"] == slice_id:
            return s
    return None


def features_for_map() -> List[Dict[str, Any]]:
    """Adapter for scripts/feature_map.py display."""
    out: List[Dict[str, Any]] = []
    for s in SLICES:
        if s["id"] in ("dashboard", "exports-ical"):
            continue
        entry: Dict[str, Any] = {
            "name": s["name"],
            "logic": list(s.get("logic", [])),
            "ui": [f"{p} tab" for p in s.get("ui_pages", [])],
            "cli": list(s.get("cli", [])),
            "perm": " / ".join(s.get("permissions", [])[:2]),
        }
        if s.get("logic_extra"):
            entry["extra"] = list(s["logic_extra"])
        out.append(entry)
    return out
