"""baseline: reflect existing sqlite schema

Revision ID: 8286dcadb953
Revises:
Create Date: 2026-07-24 01:59:06.019485

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8286dcadb953"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "certification_types",
        sa.Column("id", sa.INTEGER(), nullable=True),
        sa.Column("code", sa.TEXT(), nullable=False),
        sa.Column("name", sa.TEXT(), nullable=False),
        sa.Column("description", sa.TEXT(), nullable=True),
        sa.Column("active", sa.INTEGER(), server_default=sa.text("1"), nullable=True),
        sa.Column("category", sa.TEXT(), server_default=sa.text("'certification'"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "department_settings",
        sa.Column("key", sa.TEXT(), nullable=True),
        sa.Column("value", sa.TEXT(), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "holidays",
        sa.Column("id", sa.INTEGER(), nullable=True),
        sa.Column("holiday_date", sa.DATE(), nullable=False),
        sa.Column("name", sa.TEXT(), nullable=False),
        sa.Column("is_paid", sa.INTEGER(), server_default=sa.text("1"), nullable=True),
        sa.Column("notes", sa.TEXT(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("holiday_date"),
    )
    op.create_index("idx_holidays_date", "holidays", ["holiday_date"], unique=False)
    op.create_table(
        "leave_accrual_ledger",
        sa.Column("id", sa.INTEGER(), nullable=True),
        sa.Column("officer_id", sa.INTEGER(), nullable=False),
        sa.Column("request_id", sa.INTEGER(), nullable=True),
        sa.Column("request_type", sa.TEXT(), nullable=True),
        sa.Column("request_date", sa.TEXT(), nullable=True),
        sa.Column("bank_column", sa.TEXT(), nullable=True),
        sa.Column("hours", sa.REAL(), nullable=True),
        sa.Column("balance_after", sa.REAL(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
        sa.Column("created_by_user_id", sa.INTEGER(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "notify_outbox",
        sa.Column("id", sa.INTEGER(), nullable=True),
        sa.Column("channel", sa.TEXT(), nullable=False),
        sa.Column("template_key", sa.TEXT(), nullable=True),
        sa.Column("subject", sa.TEXT(), nullable=True),
        sa.Column("body", sa.TEXT(), nullable=True),
        sa.Column("officer_id", sa.INTEGER(), nullable=True),
        sa.Column("recipient", sa.TEXT(), nullable=True),
        sa.Column("status", sa.TEXT(), server_default=sa.text("'queued'"), nullable=False),
        sa.Column("attempts", sa.INTEGER(), server_default=sa.text("0"), nullable=True),
        sa.Column("last_error", sa.TEXT(), nullable=True),
        sa.Column("provider_ref", sa.TEXT(), nullable=True),
        sa.Column("meta_json", sa.TEXT(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
        sa.Column("sent_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("user_id", sa.INTEGER(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_notify_outbox_status", "notify_outbox", ["status", "created_at"], unique=False)
    op.create_table(
        "officers",
        sa.Column("id", sa.INTEGER(), nullable=True),
        sa.Column("name", sa.TEXT(), nullable=False),
        sa.Column("seniority_rank", sa.INTEGER(), nullable=False),
        sa.Column("squad", sa.TEXT(), nullable=True),
        sa.Column("shift_start", sa.TEXT(), nullable=True),
        sa.Column("shift_end", sa.TEXT(), nullable=True),
        sa.Column("pay_rate", sa.REAL(), server_default=sa.text("(30.0)"), nullable=True),
        sa.Column("night_differential_rate", sa.REAL(), server_default=sa.text("(1.0)"), nullable=True),
        sa.Column("photo_path", sa.TEXT(), nullable=True),
        sa.Column("active", sa.INTEGER(), server_default=sa.text("1"), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
        sa.Column("start_date", sa.DATE(), nullable=True),
        sa.Column("email", sa.TEXT(), nullable=True),
        sa.Column("phone", sa.TEXT(), nullable=True),
        sa.Column("address", sa.TEXT(), nullable=True),
        sa.Column("job_title", sa.TEXT(), nullable=True),
        sa.Column("annual_hours_target", sa.REAL(), server_default=sa.text("(2080)"), nullable=True),
        sa.Column("overtime_multiplier", sa.REAL(), server_default=sa.text("(1.5)"), nullable=True),
        sa.Column("station", sa.TEXT(), nullable=True),
        sa.Column("workforce_class", sa.TEXT(), server_default=sa.text("'sworn'"), nullable=True),
        sa.Column("rotation_pattern", sa.TEXT(), nullable=True),
        sa.Column("rotation_phase", sa.INTEGER(), server_default=sa.text("0"), nullable=True),
        sa.Column("max_turn_downs_year", sa.INTEGER(), nullable=True),
        sa.Column("max_ordered_in_year", sa.INTEGER(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "optimizer_jobs",
        sa.Column("id", sa.TEXT(), nullable=True),
        sa.Column("status", sa.TEXT(), server_default=sa.text("'queued'"), nullable=False),
        sa.Column("params_json", sa.TEXT(), nullable=False),
        sa.Column("result_json", sa.TEXT(), nullable=True),
        sa.Column("error_text", sa.TEXT(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
        sa.Column("updated_at", sa.TIMESTAMP(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_optimizer_jobs_created", "optimizer_jobs", ["created_at"], unique=False)
    op.create_table(
        "shift_bid_events",
        sa.Column("id", sa.INTEGER(), nullable=True),
        sa.Column("title", sa.TEXT(), nullable=True),
        sa.Column("status", sa.TEXT(), server_default=sa.text("'draft'"), nullable=True),
        sa.Column("number_of_shifts", sa.TEXT(), nullable=True),
        sa.Column("shift_length", sa.TEXT(), nullable=True),
        sa.Column("rotation", sa.TEXT(), nullable=True),
        sa.Column("shift_start_times", sa.TEXT(), nullable=True),
        sa.Column("shifts_begin", sa.TEXT(), nullable=True),
        sa.Column("bids_due_by", sa.TEXT(), nullable=True),
        sa.Column("squad", sa.TEXT(), nullable=True),
        sa.Column("notes", sa.TEXT(), nullable=True),
        sa.Column("created_by_user_id", sa.INTEGER(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
        sa.Column("published_at", sa.TEXT(), nullable=True),
        sa.Column("finalized_at", sa.TEXT(), nullable=True),
        sa.Column("rotation_json", sa.TEXT(), nullable=True),
        sa.Column("simulation_id", sa.INTEGER(), nullable=True),
        sa.Column("bids_closed_at", sa.TEXT(), nullable=True),
        sa.CheckConstraint("squad IN ('A', 'B') OR squad IS NULL"),
        sa.CheckConstraint("status IN ('draft', 'open', 'finalized', 'cancelled')"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "simulator_scenarios",
        sa.Column("id", sa.INTEGER(), nullable=True),
        sa.Column("name", sa.TEXT(), nullable=False),
        sa.Column("config_json", sa.TEXT(), nullable=False),
        sa.Column("result_json", sa.TEXT(), nullable=True),
        sa.Column("notes", sa.TEXT(), nullable=True),
        sa.Column("created_by_user_id", sa.INTEGER(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_simulator_scenarios_created", "simulator_scenarios", ["created_at"], unique=False)
    op.create_table(
        "station_posts",
        sa.Column("id", sa.INTEGER(), nullable=True),
        sa.Column("code", sa.TEXT(), nullable=False),
        sa.Column("name", sa.TEXT(), nullable=False),
        sa.Column("min_staff", sa.INTEGER(), server_default=sa.text("1"), nullable=True),
        sa.Column("active", sa.INTEGER(), server_default=sa.text("1"), nullable=True),
        sa.Column("notes", sa.TEXT(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "app_users",
        sa.Column("id", sa.INTEGER(), nullable=True),
        sa.Column("officer_id", sa.INTEGER(), nullable=True),
        sa.Column("username", sa.TEXT(), nullable=False),
        sa.Column("password", sa.TEXT(), nullable=False),
        sa.Column("role", sa.TEXT(), nullable=False),
        sa.Column("active", sa.INTEGER(), server_default=sa.text("1"), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
        sa.Column("must_change_password", sa.INTEGER(), server_default=sa.text("0"), nullable=True),
        sa.Column("mfa_secret", sa.TEXT(), nullable=True),
        sa.Column("mfa_enabled", sa.INTEGER(), server_default=sa.text("0"), nullable=True),
        sa.Column("mfa_enrolled_at", sa.TIMESTAMP(), nullable=True),
        sa.CheckConstraint("role IN ('Officer', 'Supervisor', 'Administration')"),
        sa.ForeignKeyConstraint(
            ["officer_id"],
            ["officers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "callback_events",
        sa.Column("id", sa.INTEGER(), nullable=True),
        sa.Column("officer_id", sa.INTEGER(), nullable=False),
        sa.Column("event_date", sa.DATE(), nullable=False),
        sa.Column("hours", sa.REAL(), nullable=False),
        sa.Column("notes", sa.TEXT(), nullable=True),
        sa.Column("created_by_user_id", sa.INTEGER(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
        sa.ForeignKeyConstraint(
            ["officer_id"],
            ["officers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_callback_events_officer", "callback_events", ["officer_id"], unique=False)
    op.create_table(
        "callback_rotation",
        sa.Column("id", sa.INTEGER(), nullable=True),
        sa.Column("officer_id", sa.INTEGER(), nullable=False),
        sa.Column("sort_order", sa.INTEGER(), nullable=False),
        sa.Column("active", sa.INTEGER(), server_default=sa.text("1"), nullable=True),
        sa.Column("notes", sa.TEXT(), nullable=True),
        sa.Column("updated_at", sa.TIMESTAMP(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
        sa.ForeignKeyConstraint(
            ["officer_id"],
            ["officers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("officer_id"),
    )
    op.create_table(
        "day_off_requests",
        sa.Column("id", sa.INTEGER(), nullable=True),
        sa.Column("officer_id", sa.INTEGER(), nullable=False),
        sa.Column("request_date", sa.DATE(), nullable=False),
        sa.Column("request_type", sa.TEXT(), nullable=False),
        sa.Column("status", sa.TEXT(), server_default=sa.text("'Pending'"), nullable=True),
        sa.Column("notes", sa.TEXT(), nullable=True),
        sa.Column("admin_notes", sa.TEXT(), nullable=True),
        sa.Column("processed_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
        sa.ForeignKeyConstraint(
            ["officer_id"],
            ["officers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_requests_date", "day_off_requests", ["request_date"], unique=False)
    op.create_index("idx_requests_status", "day_off_requests", ["status"], unique=False)
    op.create_table(
        "geofence_punches",
        sa.Column("id", sa.INTEGER(), nullable=True),
        sa.Column("officer_id", sa.INTEGER(), nullable=False),
        sa.Column("punch_type", sa.TEXT(), nullable=False),
        sa.Column("lat", sa.REAL(), nullable=True),
        sa.Column("lon", sa.REAL(), nullable=True),
        sa.Column("accuracy_m", sa.REAL(), nullable=True),
        sa.Column("within_fence", sa.INTEGER(), nullable=True),
        sa.Column("distance_m", sa.REAL(), nullable=True),
        sa.Column("notes", sa.TEXT(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
        sa.Column("edited", sa.INTEGER(), server_default=sa.text("0"), nullable=True),
        sa.Column("original_created_at", sa.TIMESTAMP(), nullable=True),
        sa.ForeignKeyConstraint(
            ["officer_id"],
            ["officers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "leave_donations",
        sa.Column("id", sa.INTEGER(), nullable=True),
        sa.Column("donor_officer_id", sa.INTEGER(), nullable=False),
        sa.Column("recipient_officer_id", sa.INTEGER(), nullable=False),
        sa.Column("bank_type", sa.TEXT(), nullable=False),
        sa.Column("hours", sa.REAL(), nullable=False),
        sa.Column("notes", sa.TEXT(), nullable=True),
        sa.Column("status", sa.TEXT(), server_default=sa.text("'completed'"), nullable=True),
        sa.Column("created_by_user_id", sa.INTEGER(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
        sa.ForeignKeyConstraint(
            ["donor_officer_id"],
            ["officers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["recipient_officer_id"],
            ["officers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_leave_donations_donor", "leave_donations", ["donor_officer_id"], unique=False)
    op.create_index("idx_leave_donations_recipient", "leave_donations", ["recipient_officer_id"], unique=False)
    op.create_table(
        "notifications",
        sa.Column("id", sa.INTEGER(), nullable=True),
        sa.Column("recipient_officer_id", sa.INTEGER(), nullable=False),
        sa.Column("type", sa.TEXT(), nullable=False),
        sa.Column("title", sa.TEXT(), nullable=False),
        sa.Column("message", sa.TEXT(), nullable=False),
        sa.Column("is_read", sa.INTEGER(), server_default=sa.text("0"), nullable=True),
        sa.Column("related_id", sa.INTEGER(), nullable=True),
        sa.Column("related_type", sa.TEXT(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
        sa.ForeignKeyConstraint(
            ["recipient_officer_id"],
            ["officers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_notifications_recipient", "notifications", ["recipient_officer_id", "is_read"], unique=False)
    op.create_table(
        "officer_availability",
        sa.Column("id", sa.INTEGER(), nullable=True),
        sa.Column("officer_id", sa.INTEGER(), nullable=False),
        sa.Column("unavailable_date", sa.DATE(), nullable=False),
        sa.Column("reason", sa.TEXT(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
        sa.ForeignKeyConstraint(
            ["officer_id"],
            ["officers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("officer_id", "unavailable_date"),
    )
    op.create_index("idx_availability_date", "officer_availability", ["unavailable_date"], unique=False)
    op.create_index(
        "idx_availability_officer", "officer_availability", ["officer_id", "unavailable_date"], unique=False
    )
    op.create_table(
        "officer_certifications",
        sa.Column("id", sa.INTEGER(), nullable=True),
        sa.Column("officer_id", sa.INTEGER(), nullable=False),
        sa.Column("cert_type_id", sa.INTEGER(), nullable=False),
        sa.Column("issued_date", sa.DATE(), nullable=True),
        sa.Column("expires_date", sa.DATE(), nullable=True),
        sa.Column("notes", sa.TEXT(), nullable=True),
        sa.ForeignKeyConstraint(
            ["cert_type_id"],
            ["certification_types.id"],
        ),
        sa.ForeignKeyConstraint(
            ["officer_id"],
            ["officers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("officer_id", "cert_type_id"),
    )
    op.create_table(
        "officer_time_banks",
        sa.Column("officer_id", sa.INTEGER(), nullable=True),
        sa.Column("comp_hours", sa.REAL(), server_default=sa.text("0"), nullable=True),
        sa.Column("sick_hours", sa.REAL(), server_default=sa.text("0"), nullable=True),
        sa.Column("float_holiday_hours", sa.REAL(), server_default=sa.text("0"), nullable=True),
        sa.Column("holiday_hours", sa.REAL(), server_default=sa.text("0"), nullable=True),
        sa.Column("sick_accrual_month", sa.TEXT(), nullable=True),
        sa.Column("annual_accrual_year", sa.INTEGER(), nullable=True),
        sa.ForeignKeyConstraint(
            ["officer_id"],
            ["officers.id"],
        ),
        sa.PrimaryKeyConstraint("officer_id"),
    )
    op.create_table(
        "open_shifts",
        sa.Column("id", sa.INTEGER(), nullable=True),
        sa.Column("shift_date", sa.DATE(), nullable=False),
        sa.Column("shift_start", sa.TEXT(), nullable=False),
        sa.Column("shift_end", sa.TEXT(), nullable=False),
        sa.Column("squad", sa.TEXT(), nullable=True),
        sa.Column("status", sa.TEXT(), server_default=sa.text("'open'"), nullable=True),
        sa.Column("notes", sa.TEXT(), nullable=True),
        sa.Column("filled_by_officer_id", sa.INTEGER(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
        sa.Column("station", sa.TEXT(), nullable=True),
        sa.CheckConstraint("squad IN ('A', 'B')"),
        sa.CheckConstraint("status IN ('open', 'filled', 'cancelled')"),
        sa.ForeignKeyConstraint(
            ["filled_by_officer_id"],
            ["officers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_open_shifts_date", "open_shifts", ["shift_date", "status"], unique=False)
    op.create_table(
        "ot_equity_ledger",
        sa.Column("id", sa.INTEGER(), nullable=True),
        sa.Column("officer_id", sa.INTEGER(), nullable=False),
        sa.Column("entry_type", sa.TEXT(), nullable=False),
        sa.Column("hours", sa.REAL(), server_default=sa.text("0"), nullable=False),
        sa.Column("event_date", sa.DATE(), nullable=True),
        sa.Column("source", sa.TEXT(), nullable=True),
        sa.Column("source_id", sa.INTEGER(), nullable=True),
        sa.Column("notes", sa.TEXT(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
        sa.Column("created_by_user_id", sa.INTEGER(), nullable=True),
        sa.ForeignKeyConstraint(
            ["officer_id"],
            ["officers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_ot_equity_officer", "ot_equity_ledger", ["officer_id", "entry_type"], unique=False)
    op.create_table(
        "ot_fill_events",
        sa.Column("id", sa.INTEGER(), nullable=True),
        sa.Column("officer_id", sa.INTEGER(), nullable=False),
        sa.Column("event_year", sa.INTEGER(), nullable=False),
        sa.Column("event_date", sa.DATE(), nullable=False),
        sa.Column("event_type", sa.TEXT(), nullable=False),
        sa.Column("fill_mode", sa.TEXT(), nullable=True),
        sa.Column("request_id", sa.INTEGER(), nullable=True),
        sa.Column("hours", sa.REAL(), server_default=sa.text("0"), nullable=True),
        sa.Column("is_partial", sa.INTEGER(), server_default=sa.text("0"), nullable=True),
        sa.Column("is_ordered", sa.INTEGER(), server_default=sa.text("0"), nullable=True),
        sa.Column("covered_shift_start", sa.TEXT(), nullable=True),
        sa.Column("notes", sa.TEXT(), nullable=True),
        sa.Column("created_by_user_id", sa.INTEGER(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
        sa.ForeignKeyConstraint(
            ["officer_id"],
            ["officers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_ot_fill_date", "ot_fill_events", ["event_date"], unique=False)
    op.create_index("idx_ot_fill_officer_year", "ot_fill_events", ["officer_id", "event_year"], unique=False)
    op.create_table(
        "payroll_entries",
        sa.Column("id", sa.INTEGER(), nullable=True),
        sa.Column("officer_id", sa.INTEGER(), nullable=False),
        sa.Column("entry_date", sa.DATE(), nullable=False),
        sa.Column("entry_type", sa.TEXT(), nullable=False),
        sa.Column("hours", sa.REAL(), nullable=False),
        sa.Column("night_differential_hours", sa.REAL(), server_default=sa.text("0"), nullable=True),
        sa.Column("calculated_pay", sa.REAL(), server_default=sa.text("0"), nullable=True),
        sa.Column("notes", sa.TEXT(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
        sa.Column("comp_bank_delta", sa.REAL(), server_default=sa.text("0"), nullable=True),
        sa.Column("sick_bank_delta", sa.REAL(), server_default=sa.text("0"), nullable=True),
        sa.Column("float_holiday_bank_delta", sa.REAL(), server_default=sa.text("0"), nullable=True),
        sa.Column("holiday_bank_delta", sa.REAL(), server_default=sa.text("0"), nullable=True),
        sa.Column("pay_period_start", sa.DATE(), nullable=True),
        sa.ForeignKeyConstraint(
            ["officer_id"],
            ["officers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_payroll_date", "payroll_entries", ["entry_date"], unique=False)
    op.create_index("idx_payroll_officer", "payroll_entries", ["officer_id"], unique=False)
    op.create_index("idx_payroll_officer_period", "payroll_entries", ["officer_id", "pay_period_start"], unique=False)
    op.create_index("idx_payroll_period", "payroll_entries", ["pay_period_start"], unique=False)
    op.create_table(
        "schedule_overrides",
        sa.Column("id", sa.INTEGER(), nullable=True),
        sa.Column("override_date", sa.DATE(), nullable=False),
        sa.Column("original_officer_id", sa.INTEGER(), nullable=False),
        sa.Column("replacement_officer_id", sa.INTEGER(), nullable=True),
        sa.Column("reason", sa.TEXT(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
        sa.Column("covered_shift_start", sa.TEXT(), nullable=True),
        sa.Column("relaxed_constraint", sa.TEXT(), nullable=True),
        sa.Column("override_authority_user_id", sa.INTEGER(), nullable=True),
        sa.Column("override_subject", sa.TEXT(), nullable=True),
        sa.Column("override_interval_start", sa.TEXT(), nullable=True),
        sa.Column("override_interval_end", sa.TEXT(), nullable=True),
        sa.Column("override_expires_at", sa.TEXT(), nullable=True),
        sa.Column("override_reason", sa.TEXT(), nullable=True),
        sa.Column("override_evidence", sa.TEXT(), nullable=True),
        sa.ForeignKeyConstraint(
            ["original_officer_id"],
            ["officers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["replacement_officer_id"],
            ["officers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_overrides_date", "schedule_overrides", ["override_date"], unique=False)
    op.create_index(
        "idx_overrides_original", "schedule_overrides", ["original_officer_id", "override_date"], unique=False
    )
    op.create_index(
        "idx_overrides_replacement", "schedule_overrides", ["replacement_officer_id", "override_date"], unique=False
    )
    op.create_table(
        "shift_bid_options",
        sa.Column("id", sa.INTEGER(), nullable=True),
        sa.Column("event_id", sa.INTEGER(), nullable=False),
        sa.Column("option_number", sa.INTEGER(), nullable=False),
        sa.Column("label", sa.TEXT(), nullable=False),
        sa.Column("status", sa.TEXT(), server_default=sa.text("'open'"), nullable=True),
        sa.Column("awarded_officer_id", sa.INTEGER(), nullable=True),
        sa.Column("shift_start", sa.TEXT(), nullable=True),
        sa.Column("shift_date", sa.TEXT(), nullable=True),
        sa.CheckConstraint("status IN ('open', 'awarded', 'unassigned')"),
        sa.ForeignKeyConstraint(
            ["awarded_officer_id"],
            ["officers.id"],
        ),
        sa.ForeignKeyConstraint(["event_id"], ["shift_bid_events.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_id", "option_number"),
    )
    op.create_index("idx_shift_bid_options_event", "shift_bid_options", ["event_id"], unique=False)
    op.create_table(
        "shift_cert_requirements",
        sa.Column("id", sa.INTEGER(), nullable=True),
        sa.Column("shift_start", sa.TEXT(), nullable=False),
        sa.Column("cert_type_id", sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cert_type_id"],
            ["certification_types.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("shift_start", "cert_type_id"),
    )
    op.create_table(
        "shift_swaps",
        sa.Column("id", sa.INTEGER(), nullable=True),
        sa.Column("swap_date", sa.DATE(), nullable=False),
        sa.Column("officer1_id", sa.INTEGER(), nullable=False),
        sa.Column("officer2_id", sa.INTEGER(), nullable=False),
        sa.Column("status", sa.TEXT(), server_default=sa.text("'Pending'"), nullable=True),
        sa.Column("admin_notes", sa.TEXT(), nullable=True),
        sa.Column("processed_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
        sa.ForeignKeyConstraint(
            ["officer1_id"],
            ["officers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["officer2_id"],
            ["officers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "audit_log",
        sa.Column("id", sa.INTEGER(), nullable=True),
        sa.Column("action", sa.TEXT(), nullable=False),
        sa.Column("entity_type", sa.TEXT(), nullable=True),
        sa.Column("entity_id", sa.INTEGER(), nullable=True),
        sa.Column("user_id", sa.INTEGER(), nullable=True),
        sa.Column("details", sa.TEXT(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
        sa.Column("prev_hash", sa.TEXT(), nullable=True),
        sa.Column("row_hash", sa.TEXT(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_audit_created", "audit_log", ["created_at"], unique=False)
    op.create_table(
        "punch_edit_requests",
        sa.Column("id", sa.INTEGER(), nullable=True),
        sa.Column("punch_id", sa.INTEGER(), nullable=False),
        sa.Column("officer_id", sa.INTEGER(), nullable=False),
        sa.Column("requested_by_user_id", sa.INTEGER(), nullable=True),
        sa.Column("current_punch_type", sa.TEXT(), nullable=True),
        sa.Column("current_created_at", sa.TEXT(), nullable=True),
        sa.Column("proposed_punch_type", sa.TEXT(), nullable=True),
        sa.Column("proposed_created_at", sa.TEXT(), nullable=True),
        sa.Column("reason", sa.TEXT(), nullable=True),
        sa.Column("status", sa.TEXT(), server_default=sa.text("'pending'"), nullable=False),
        sa.Column("reviewed_by_user_id", sa.INTEGER(), nullable=True),
        sa.Column("review_notes", sa.TEXT(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
        sa.Column("reviewed_at", sa.TIMESTAMP(), nullable=True),
        sa.ForeignKeyConstraint(
            ["officer_id"],
            ["officers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["punch_id"],
            ["geofence_punches.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_punch_edit_status", "punch_edit_requests", ["status", "created_at"], unique=False)
    op.create_table(
        "schedule_snapshots",
        sa.Column("id", sa.INTEGER(), nullable=True),
        sa.Column("year", sa.INTEGER(), nullable=False),
        sa.Column("month", sa.INTEGER(), nullable=False),
        sa.Column("schedule_type", sa.TEXT(), nullable=False),
        sa.Column("locked", sa.INTEGER(), server_default=sa.text("0"), nullable=True),
        sa.Column("generated_at", sa.TIMESTAMP(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
        sa.Column("generated_by_user_id", sa.INTEGER(), nullable=True),
        sa.Column("notes", sa.TEXT(), nullable=True),
        sa.CheckConstraint("schedule_type IN ('base', 'updated')"),
        sa.ForeignKeyConstraint(
            ["generated_by_user_id"],
            ["app_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("year", "month", "schedule_type"),
    )
    op.create_table(
        "shift_bid_rankings",
        sa.Column("id", sa.INTEGER(), nullable=True),
        sa.Column("event_id", sa.INTEGER(), nullable=False),
        sa.Column("officer_id", sa.INTEGER(), nullable=False),
        sa.Column("option_id", sa.INTEGER(), nullable=False),
        sa.Column("preference_rank", sa.INTEGER(), nullable=False),
        sa.Column("submitted_at", sa.TIMESTAMP(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
        sa.ForeignKeyConstraint(["event_id"], ["shift_bid_events.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["officer_id"],
            ["officers.id"],
        ),
        sa.ForeignKeyConstraint(["option_id"], ["shift_bid_options.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_id", "officer_id", "option_id"),
        sa.UniqueConstraint("event_id", "officer_id", "preference_rank"),
    )
    op.create_index("idx_shift_bid_rankings_event", "shift_bid_rankings", ["event_id"], unique=False)
    op.create_table(
        "timecard_approvals",
        sa.Column("id", sa.INTEGER(), nullable=True),
        sa.Column("officer_id", sa.INTEGER(), nullable=False),
        sa.Column("pay_period_start", sa.DATE(), nullable=False),
        sa.Column("status", sa.TEXT(), server_default=sa.text("'Draft'"), nullable=False),
        sa.Column("submitted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("approved_by_user_id", sa.INTEGER(), nullable=True),
        sa.Column("approved_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("supervisor_notes", sa.TEXT(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
        sa.Column("updated_at", sa.TIMESTAMP(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
        sa.CheckConstraint("status IN ('Draft', 'Submitted', 'Approved', 'Rejected')"),
        sa.ForeignKeyConstraint(
            ["approved_by_user_id"],
            ["app_users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["officer_id"],
            ["officers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("officer_id", "pay_period_start"),
    )
    op.create_index(
        "idx_timecard_approval_officer", "timecard_approvals", ["officer_id", "pay_period_start"], unique=False
    )
    op.create_index("idx_timecard_approval_period", "timecard_approvals", ["pay_period_start"], unique=False)
    op.create_table(
        "timecard_entries",
        sa.Column("id", sa.INTEGER(), nullable=True),
        sa.Column("officer_id", sa.INTEGER(), nullable=False),
        sa.Column("pay_period_start", sa.DATE(), nullable=False),
        sa.Column("entry_date", sa.DATE(), nullable=False),
        sa.Column("hours_worked", sa.REAL(), server_default=sa.text("0"), nullable=True),
        sa.Column("time_in", sa.TEXT(), nullable=True),
        sa.Column("time_out", sa.TEXT(), nullable=True),
        sa.Column("entry_type", sa.TEXT(), server_default=sa.text("'Regular Hours'"), nullable=True),
        sa.Column("night_diff_hours", sa.REAL(), server_default=sa.text("0"), nullable=True),
        sa.Column("notes", sa.TEXT(), nullable=True),
        sa.Column("payroll_entry_id", sa.INTEGER(), nullable=True),
        sa.Column("imported_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
        sa.Column("updated_at", sa.TIMESTAMP(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
        sa.ForeignKeyConstraint(
            ["officer_id"],
            ["officers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["payroll_entry_id"],
            ["payroll_entries.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_timecard_date", "timecard_entries", ["entry_date"], unique=False)
    op.create_index("idx_timecard_officer_date", "timecard_entries", ["officer_id", "entry_date"], unique=False)
    op.create_index("idx_timecard_officer_period", "timecard_entries", ["officer_id", "pay_period_start"], unique=False)
    op.create_table(
        "schedule_snapshot_rows",
        sa.Column("id", sa.INTEGER(), nullable=True),
        sa.Column("snapshot_id", sa.INTEGER(), nullable=False),
        sa.Column("assignment_date", sa.DATE(), nullable=False),
        sa.Column("officer_id", sa.INTEGER(), nullable=False),
        sa.Column("status", sa.TEXT(), nullable=False),
        sa.Column("shift_start", sa.TEXT(), nullable=True),
        sa.Column("shift_end", sa.TEXT(), nullable=True),
        sa.Column("is_manual", sa.INTEGER(), server_default=sa.text("0"), nullable=True),
        sa.Column("notes", sa.TEXT(), nullable=True),
        sa.ForeignKeyConstraint(
            ["officer_id"],
            ["officers.id"],
        ),
        sa.ForeignKeyConstraint(["snapshot_id"], ["schedule_snapshots.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("snapshot_id", "assignment_date", "officer_id"),
    )
    op.create_index(
        "idx_snapshot_rows_date", "schedule_snapshot_rows", ["snapshot_id", "assignment_date"], unique=False
    )
    op.create_index(
        "idx_snapshot_rows_officer", "schedule_snapshot_rows", ["officer_id", "assignment_date"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_snapshot_rows_officer", table_name="schedule_snapshot_rows")
    op.drop_index("idx_snapshot_rows_date", table_name="schedule_snapshot_rows")
    op.drop_table("schedule_snapshot_rows")
    op.drop_index("idx_timecard_officer_period", table_name="timecard_entries")
    op.drop_index("idx_timecard_officer_date", table_name="timecard_entries")
    op.drop_index("idx_timecard_date", table_name="timecard_entries")
    op.drop_table("timecard_entries")
    op.drop_index("idx_timecard_approval_period", table_name="timecard_approvals")
    op.drop_index("idx_timecard_approval_officer", table_name="timecard_approvals")
    op.drop_table("timecard_approvals")
    op.drop_index("idx_shift_bid_rankings_event", table_name="shift_bid_rankings")
    op.drop_table("shift_bid_rankings")
    op.drop_table("schedule_snapshots")
    op.drop_index("idx_punch_edit_status", table_name="punch_edit_requests")
    op.drop_table("punch_edit_requests")
    op.drop_index("idx_audit_created", table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_table("shift_swaps")
    op.drop_table("shift_cert_requirements")
    op.drop_index("idx_shift_bid_options_event", table_name="shift_bid_options")
    op.drop_table("shift_bid_options")
    op.drop_index("idx_overrides_replacement", table_name="schedule_overrides")
    op.drop_index("idx_overrides_original", table_name="schedule_overrides")
    op.drop_index("idx_overrides_date", table_name="schedule_overrides")
    op.drop_table("schedule_overrides")
    op.drop_index("idx_payroll_period", table_name="payroll_entries")
    op.drop_index("idx_payroll_officer_period", table_name="payroll_entries")
    op.drop_index("idx_payroll_officer", table_name="payroll_entries")
    op.drop_index("idx_payroll_date", table_name="payroll_entries")
    op.drop_table("payroll_entries")
    op.drop_index("idx_ot_fill_officer_year", table_name="ot_fill_events")
    op.drop_index("idx_ot_fill_date", table_name="ot_fill_events")
    op.drop_table("ot_fill_events")
    op.drop_index("idx_ot_equity_officer", table_name="ot_equity_ledger")
    op.drop_table("ot_equity_ledger")
    op.drop_index("idx_open_shifts_date", table_name="open_shifts")
    op.drop_table("open_shifts")
    op.drop_table("officer_time_banks")
    op.drop_table("officer_certifications")
    op.drop_index("idx_availability_officer", table_name="officer_availability")
    op.drop_index("idx_availability_date", table_name="officer_availability")
    op.drop_table("officer_availability")
    op.drop_index("idx_notifications_recipient", table_name="notifications")
    op.drop_table("notifications")
    op.drop_index("idx_leave_donations_recipient", table_name="leave_donations")
    op.drop_index("idx_leave_donations_donor", table_name="leave_donations")
    op.drop_table("leave_donations")
    op.drop_table("geofence_punches")
    op.drop_index("idx_requests_status", table_name="day_off_requests")
    op.drop_index("idx_requests_date", table_name="day_off_requests")
    op.drop_table("day_off_requests")
    op.drop_table("callback_rotation")
    op.drop_index("idx_callback_events_officer", table_name="callback_events")
    op.drop_table("callback_events")
    op.drop_table("app_users")
    op.drop_table("station_posts")
    op.drop_index("idx_simulator_scenarios_created", table_name="simulator_scenarios")
    op.drop_table("simulator_scenarios")
    op.drop_table("shift_bid_events")
    op.drop_index("idx_optimizer_jobs_created", table_name="optimizer_jobs")
    op.drop_table("optimizer_jobs")
    op.drop_table("officers")
    op.drop_index("idx_notify_outbox_status", table_name="notify_outbox")
    op.drop_table("notify_outbox")
    op.drop_table("leave_accrual_ledger")
    op.drop_index("idx_holidays_date", table_name="holidays")
    op.drop_table("holidays")
    op.drop_table("department_settings")
    op.drop_table("certification_types")
    # ### end Alembic commands ###
